#!/usr/bin/env python3

""" Generated by copilot but beautified by myself.

- Q#1: isn't there a realiable python script for me to dump what are
  the physical ethernet interfaces and my wifi interfaces?
  + ...instead of `C:/Users/henrique>netsh interface ip show config`

"""

# pylint: disable=missing-function-docstring

import json
import socket
import psutil

def main():
    list_them()

def list_them():
    """ List my interfaces. """
    res = get_my_interfaces()
    print(tostring(res))
    own, virtual = res["own"], res["virtual"]
    print(f'### own (len={len(own)}):')		# Lists own interfaces
    for idx, key in enumerate(sorted(own), 1):
        print(f"### ({idx}/{len(own)}):", key, resume(own[key]), end="\n\n")
    if virtual:
        print("### box:", sorted(res["virtual"]))
    return res

def get_interfaces():
    """ Wrapper to get network interfaces! """
    return get_my_interfaces()

def get_my_interfaces():
    """ Retrieve my interfaces. """
    interfaces = {}
    addrs = psutil.net_if_addrs()
    stats = psutil.net_if_stats()
    for iface, addr_list in addrs.items():
        iface_info = {
            "type": classify_interface(iface),
            "is_up": stats[iface].isup,
            "speed_mbps": stats[iface].speed,
            "addresses": [],
        }
        for addr in addr_list:
            iface_info["addresses"].append(itemized(addr))
        interfaces[iface] = iface_info
    res = split_ifs(interfaces)
    return res

def classify_interface(name):
    """ Major (lan/ wifi) Interface Classification """
    if "Wi-Fi" in name or "Wireless" in name:
        return "wifi"
    if "Ethernet" in name:
        return "ethernet"
    return "other"

def itemized(addr):
    """ Returns a dictionary based information. """
    def family_iface(family):
        return family_name(family)
    item = {
        "family": family_iface(addr.family),  # AddressFamily(addr.family) for -1 does not work
        "address": addr.address,
        "netmask": addr.netmask,
        "broadcast": addr.broadcast
    }
    return item

def family_name(fam):
    """ Return human-readable family name for an address family integer. """
    assert isinstance(fam, int), f"Bogus family (listed): {[fam]}"
    fam_name = getattr(socket, "AddressFamily")
    if fam_name is not None:
        return "AF_LINK" if fam == -1 else fam_name(fam).name
    if fam == socket.AF_INET:
        astr = "AF_INET"
    elif fam == socket.AF_INET6:
        astr = "AF_INET6"
    else:
        astr = str(fam)
    return astr

def resume(ifc, def_str="-"):
    """ Returns the listed addresses of an interface. """
    lst = ifc.get("addresses")
    if lst is None:
        return def_str
    # sample_str = f"(len={len(lst)}) <" + repr(["FIRST"] + lst + ["LAST"]) + ">"
    return lst

def split_ifs(interfaces):
    own = {}
    virtual = {}
    for name, info in interfaces.items():
        is_virtual = False
        # Check IP addresses for VirtualBox host-only range
        for addr in info.get("addresses", []):
            ip = addr.get("address", "")
            if ip.startswith("192.168.56."):
                is_virtual = True
                break
        if is_virtual:
            virtual[name] = info
        else:
            own[name] = info
    res = {"own": own, "virtual": virtual}
    return res

def tostring(obj):
    """ Returns the JSON equivalent """
    astr = json.dumps(obj, indent=4)
    return astr

if __name__ == "__main__":
    main()
