#!/usr/bin/env python3

""" Generated by copilot but beautified by myself.

Microsoft Adapters 'wmi' -- WMI is Windows Management Instrumentation.
"""

import wmi  # pylint: disable=import-error


def main():
    """Main entry point: collect adapters and classify them."""
    adapters = get_adapter_descriptions()
    result = split_ifs(adapters)
    print(result)

def get_adapter_descriptions():
    """Return a dictionary of network adapters keyed by description with basic info."""
    c = wmi.WMI()
    adapters = {}
    for nic in c.Win32_NetworkAdapterConfiguration(IPEnabled=True):
        adapters[nic.Description] = {
            "caption": nic.Caption,
            "mac": nic.MACAddress,
            "ip": nic.IPAddress,
            "dns": nic.DNSDomain,
        }
    return adapters

def split_ifs(adapters):
    """Split adapters into 'own' and 'virtual' groups based on description."""
    own = {}
    virtual = {}
    for desc, info in adapters.items():
        if "VirtualBox" in desc:
            virtual[desc] = info
        else:
            own[desc] = info
    return {"own": own, "virtual": virtual}

if __name__ == "__main__":
    main()
