#!/usr/bin/env python3

""" Generated by copilot but beautified by myself.

Shows NICs in Windows. This is not platform independent (Linux does not work!)

Microsoft Adapters 'wmi' -- WMI is Windows Management Instrumentation.
"""

import json
import wmi  # pylint: disable=import-error

#DEF_SHOW_ONLY_UP = False
DEF_SHOW_ONLY_UP = True

def main():
    """Main entry point: collect adapters and classify them."""
    script()

def script(tup=None):
    opt1 = DEF_SHOW_ONLY_UP if tup is None else tup[0]
    #opt1 = False   # ...show all, not only the IP 'nic'(s) that are up!
    adapters = get_adapter_descriptions(opt1)
    result = split_ifs(adapters)
    for kind in sorted(result):
        lst = result[kind]
        if not lst:
            continue
        print(f"{kind}, {len(lst)} item(s):")
        for key, adapt in lst.items():
            print(" ", key)
            for fabric, item in adapt.items():
                print("   ", quoted(fabric, ":"), item)
        print()
    return result

def get_adapter_descriptions(only_ip_up=True):
    """Return a dictionary of network adapters keyed by description with basic info."""
    c_adapt = wmi.WMI()
    if only_ip_up:
        dct = c_adapt.Win32_NetworkAdapterConfiguration(IPEnabled=True)
    else:
        dct = c_adapt.Win32_NetworkAdapterConfiguration()
    adapters = {}
    for nic in dct:
        adapters[nic.Description] = {
            "caption": nic.Caption,
            "mac": nic.MACAddress,
            "ip": nic.IPAddress,
            "dns": nic.DNSDomain,
            "up": nic.ipenabled,
            "hasDHCP": nic.DHCPEnabled,
        }
    return adapters

def split_ifs(adapters, virt_name="VirtualBox"):
    """Split adapters into 'own' and 'virtual' groups based on description."""
    own = {}
    virtual = {}
    for desc, info in adapters.items():
        key = desc
        if desc.startswith(virt_name):
            key = desc[len(virt_name):].strip().replace(" ", "@")
            virtual[key] = info
        else:
            own[key] = info
    return {"own": own, "virtual": virtual}

def quoted(name, suffix=""):
    astr = repr(DoubleQuotedStr(name))
    return astr + suffix


class DoubleQuotedStr(str):
    """ Sampled quoted text, here... for semi-JSON readability. """
    def __repr__(self):
        # Use json.dumps to guarantee double quotes and proper escaping
        return json.dumps(self)


if __name__ == "__main__":
    main()
