#!/usr/bin/env python3

""" Generated by copilot
- "what is a reliable windows 11 substitute of Linux 'tail' executable?"
-- Copilot gave me a Powershell script
- "i hate powershell, give me instead a python script to run"
- "name == 'main' should have only main(), nothing else."
- "why is [n] exactly?"
- "well, arguments should be arranged in a robust way"
- "show me my prompts"
- "sure, good, but no UTF-8 chars for quotes please, regular ASCII"

"""

import argparse
import time
import os

def tail(filename, n=10, follow=False):
    """Print the last n lines of a file, optionally follow new lines."""
    with open(filename, "r", encoding="utf-8", errors="ignore") as f:
        # Go to end of file
        f.seek(0, os.SEEK_END)
        filesize = f.tell()

        # Read backwards until we have n lines
        blocksize = 1024
        data = ""
        while filesize > 0 and data.count("\n") <= n:
            readsize = min(blocksize, filesize)
            filesize -= readsize
            f.seek(filesize)
            data = f.read(readsize) + data

        lines = data.splitlines()[-n:]
        for line in lines:
            print(line)

        if follow:
            while True:
                line = f.readline()
                if line:
                    print(line, end="")
                else:
                    time.sleep(0.5)

def main():
    """ Main script! """
    parser = argparse.ArgumentParser(
        description="Python implementation of tail (last lines of a file)."
    )
    parser.add_argument(
        "filename",
        help="Path to the file to read"
    )
    parser.add_argument(
        "-n", "--lines",
        type=int,
        default=10,
        help="Number of lines to show (default: 10)"
    )
    parser.add_argument(
        "-f", "--follow",
        action="store_true",
        help="Keep reading the file as it grows (like tail -f)"
    )

    args = parser.parse_args()
    tail(args.filename, n=args.lines, follow=args.follow)

if __name__ == "__main__":
    main()
